dist: focal

if: (type = pull_request AND branch = master)

matrix:
   include:
      -  os: linux
         env:
            - JOB_NAME: job1


script:
   - python3 check.py


notifications:
   email: false
