dist: focal


matrix:
   include:
      if: (type = pull_request AND branch = master)
         -  os: linux
            env:
               - JOB_NAME: job1


script:
   - python3 check.py


notifications:
   email: false
