dist: focal

if: (branch = master AND (type = pull_request OR type = cron))

matrix:
   include:
      -  os: linux
         env:
            - JOB_NAME: job1


script:
   - python3 check.py


notifications:
   email: false
