dist: bionic

# branches:
#    only:
#       - master

matrix:
   include:
      -  os: linux
         compiler: gcc
         language: cpp

         install:
            - python --version
            - pip --version
            - pip show requests
            - pip show urllib3
            - pip show chardet
            - python -m pip install requests


script:
   - python check.py
