language: cpp
dist: trusty
sudo: required

matrix:
   include:
      -  os: osx
         osx_image: xcode9.3
         compiler: clang
         env: CONFIGURATION=Debug   PYTHON=3.7
         before_install:
            - python --version
            # - python3 --version
            - brew install python
            - python --version
            - python3 --version
         install:
            - python --version

      -  os: osx
         osx_image: xcode7.3
         compiler: clang
         env: CONFIGURATION=Debug   PYTHON=2.7
         install:
            - python --version

      -  os: linux
         compiler: gcc
         addons:
            apt:
               packages: ['g++-4.8']
         env: COMPILER=g++-4.8   CONFIGURATION=Debug
         install:
            - python --version

      -  os: linux
         compiler: clang
         addons:
            apt:
               packages: ['clang-3.6', 'libc++-dev']
         env: COMPILER=clang++-3.6   CONFIGURATION=Debug
         install:
            - python --version



script:
  - make
  - python test.py

notifications:
  email: false
