language: cpp
dist: trusty
sudo: required
sudo: required

matrix:
   include:
      -  os: osx
         osx_image: xcode9.3
         compiler: clang
         env: CONFIGURATION=Debug   PYTHON=3
         # before_install:
         #    - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade python
         install:
            - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade python
         script:
            - make
            - python3 test.py

      -  os: osx
         osx_image: xcode7.3
         compiler: clang
         env: CONFIGURATION=Debug
         install:
            - python --version

      -  os: linux
         compiler: gcc
         addons:
            apt:
               packages: ['g++-4.8']
         env: COMPILER=g++-4.8   CONFIGURATION=Debug
         install:
            - python --version

      -  os: linux
         compiler: clang
         addons:
            apt:
               packages: ['clang-3.6', 'libc++-dev']
         env: COMPILER=clang++-3.6   CONFIGURATION=Debug
         install:
            - python --version



script:
  - make
  - python test.py

notifications:
  email: false
