clone_depth: 50

environment:
   matrix:
      - configuration: Debug
        platform: Win32

      - configuration: Debug
        platform: x64

install:
   #- set PATH=C:\Python37-x64;%PATH%
   #- set PATH=C:\Python27;%PATH%
   - set PATH=C:\Python37;%PATH%

build_script: true

test_script:
   - python test.py
