clone_depth: 50

environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
        PYTHON_PATH: "C:\\Python27"

      - CONFIGURATION: Debug
        PLATFORM: x64
        PYTHON_PATH: "C:\\Python37-x64"

install:
   #- set PATH=C:\Python37-x64;%PATH%
   #- set PATH=C:\Python27;%PATH%
   #- set PATH=C:\Python37;%PATH%
   - echo %PYTHON_PATH%
   - set PATH=%PYTHON_PATH%;%PATH%

build_script: true

test_script:
   - python test.py
